# Generated by Django 5.2.6 on 2025-09-07 12:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('shoes', 'Sepatu Bola'), ('jersey', 'Jersey'), ('ball', 'Bola'), ('equipment', 'Peralatan Latihan'), ('accessories', 'Aksesoris'), ('other', 'Lainnya')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('item_views', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
