# Generated by Django 5.2.6 on 2025-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('persona', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Sepatu Bola'), ('jersey', 'Jersey'), ('ball', 'Bola'), ('equipment', 'Peralatan Latihan'), ('accessories', 'Aksesoris'), ('other', 'Lainnya')], default='other', max_length=20),
        ),
    ]
